### ISSUE TITLE
Unable to run pip install requirements.txt

### ISSUE THREAD

**Issue by UriBarkan** [kinivi/AlchemyLab#1]
Hi,

I'm trying to run the Enhanced.ipynb notebook.

When running the installation with pip install I get the following error  (both locally and in Colab, same error):

> !pip install -r requirements.txt
> 
> Collecting accelerate==0.21.0 (from -r requirements.txt (line 1))
>   Downloading accelerate-0.21.0-py3-none-any.whl (244 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 4.0 MB/s eta 0:00:00
> Collecting aiohttp==3.9.1 (from -r requirements.txt (line 2))
>   Downloading aiohttp-3.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.8 MB/s eta 0:00:00
> Requirement already satisfied: aiosignal==1.3.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.3.1)
> Collecting aiostream==0.5.2 (from -r requirements.txt (line 4))
>   Downloading aiostream-0.5.2-py3-none-any.whl (39 kB)
> Collecting alembic==1.13.1 (from -r requirements.txt (line 5))
>   Downloading alembic-1.13.1-py3-none-any.whl (233 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 8.5 MB/s eta 0:00:00
> Collecting altair==5.2.0 (from -r requirements.txt (line 6))
>   Downloading altair-5.2.0-py3-none-any.whl (996 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 996.9/996.9 kB 12.6 MB/s eta 0:00:00
> Requirement already satisfied: annotated-types==0.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (0.6.0)
> Collecting anyio==4.2.0 (from -r requirements.txt (line 8))
>   Downloading anyio-4.2.0-py3-none-any.whl (85 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 kB 9.1 MB/s eta 0:00:00
> Requirement already satisfied: appdirs==1.4.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (1.4.4)
> Collecting appnope==0.1.3 (from -r requirements.txt (line 10))
>   Downloading appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
> Collecting asttokens==2.4.1 (from -r requirements.txt (line 11))
>   Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
> Requirement already satisfied: async-timeout==4.0.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (4.0.3)
> Requirement already satisfied: attrs==23.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (23.2.0)
> Collecting backoff==2.2.1 (from -r requirements.txt (line 14))
>   Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
> Collecting beautifulsoup4==4.12.2 (from -r requirements.txt (line 15))
>   Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 15.8 MB/s eta 0:00:00
> Collecting bitsandbytes==0.41.0 (from -r requirements.txt (line 16))
>   Downloading bitsandbytes-0.41.0-py3-none-any.whl (92.6 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 MB 9.5 MB/s eta 0:00:00
> Requirement already satisfied: bleach==6.1.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 17)) (6.1.0)
> Collecting blinker==1.7.0 (from -r requirements.txt (line 18))
>   Downloading blinker-1.7.0-py3-none-any.whl (13 kB)
> Requirement already satisfied: blis==0.7.11 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 19)) (0.7.11)
> Requirement already satisfied: cachetools==5.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 20)) (5.3.2)
> Requirement already satisfied: catalogue==2.0.10 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 21)) (2.0.10)
> Collecting certifi==2023.11.17 (from -r requirements.txt (line 22))
>   Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 17.5 MB/s eta 0:00:00
> Requirement already satisfied: charset-normalizer==3.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 23)) (3.3.2)
> Requirement already satisfied: click==8.1.7 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 24)) (8.1.7)
> Requirement already satisfied: cloudpathlib==0.16.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 25)) (0.16.0)
> Collecting cohere==4.40 (from -r requirements.txt (line 26))
>   Downloading cohere-4.40-py3-none-any.whl (51 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.7/51.7 kB 5.2 MB/s eta 0:00:00
> Collecting comm==0.2.0 (from -r requirements.txt (line 27))
>   Downloading comm-0.2.0-py3-none-any.whl (7.0 kB)
> Requirement already satisfied: confection==0.1.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 28)) (0.1.4)
> Requirement already satisfied: contourpy==1.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 29)) (1.2.0)
> Requirement already satisfied: cycler==0.12.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 30)) (0.12.1)
> Requirement already satisfied: cymem==2.0.8 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 31)) (2.0.8)
> Collecting dataclasses-json==0.5.14 (from -r requirements.txt (line 32))
>   Downloading dataclasses_json-0.5.14-py3-none-any.whl (26 kB)
> Collecting datasets==2.16.1 (from -r requirements.txt (line 33))
>   Downloading datasets-2.16.1-py3-none-any.whl (507 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 43.4 MB/s eta 0:00:00
> Collecting debugpy==1.8.0 (from -r requirements.txt (line 34))
>   Downloading debugpy-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 71.0 MB/s eta 0:00:00
> Collecting decorator==5.1.1 (from -r requirements.txt (line 35))
>   Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
> Collecting Deprecated==1.2.14 (from -r requirements.txt (line 36))
>   Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
> Collecting dill==0.3.7 (from -r requirements.txt (line 37))
>   Downloading dill-0.3.7-py3-none-any.whl (115 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 12.4 MB/s eta 0:00:00
> Requirement already satisfied: diskcache==5.6.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 38)) (5.6.3)
> Collecting distro==1.9.0 (from -r requirements.txt (line 39))
>   Downloading distro-1.9.0-py3-none-any.whl (20 kB)
> Collecting dnspython==2.4.2 (from -r requirements.txt (line 40))
>   Downloading dnspython-2.4.2-py3-none-any.whl (300 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.4/300.4 kB 23.6 MB/s eta 0:00:00
> Collecting docarray==0.32.1 (from -r requirements.txt (line 41))
>   Downloading docarray-0.32.1-py3-none-any.whl (215 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.3/215.3 kB 22.1 MB/s eta 0:00:00
> Collecting docker-pycreds==0.4.0 (from -r requirements.txt (line 42))
>   Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
> Collecting einops==0.6.1 (from -r requirements.txt (line 43))
>   Downloading einops-0.6.1-py3-none-any.whl (42 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 4.2 MB/s eta 0:00:00
> Requirement already satisfied: entrypoints==0.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 44)) (0.4)
> Requirement already satisfied: exceptiongroup==1.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 45)) (1.2.0)
> Collecting executing==2.0.1 (from -r requirements.txt (line 46))
>   Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
> ERROR: Could not find a version that satisfies the requirement faiss==1.7.4 (from versions: none)
> ERROR: No matching distribution found for faiss==1.7.4

Any idea how to fix it?

Thanks in advance.

**Comment by kinivi** [comment]
sorry for the late reply, try to remove versions int he requirements.txt and try again

**Comment by tosettil-polimi** [comment]
> Hi,
> 
> I'm trying to run the Enhanced.ipynb notebook.
> 
> When running the installation with pip install I get the following error (both locally and in Colab, same error):
> 
> > !pip install -r requirements.txt
> > Collecting accelerate==0.21.0 (from -r requirements.txt (line 1))
> > Downloading accelerate-0.21.0-py3-none-any.whl (244 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 4.0 MB/s eta 0:00:00
> > Collecting aiohttp==3.9.1 (from -r requirements.txt (line 2))
> > Downloading aiohttp-3.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.8 MB/s eta 0:00:00
> > Requirement already satisfied: aiosignal==1.3.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.3.1)
> > Collecting aiostream==0.5.2 (from -r requirements.txt (line 4))
> > Downloading aiostream-0.5.2-py3-none-any.whl (39 kB)
> > Collecting alembic==1.13.1 (from -r requirements.txt (line 5))
> > Downloading alembic-1.13.1-py3-none-any.whl (233 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 8.5 MB/s eta 0:00:00
> > Collecting altair==5.2.0 (from -r requirements.txt (line 6))
> > Downloading altair-5.2.0-py3-none-any.whl (996 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 996.9/996.9 kB 12.6 MB/s eta 0:00:00
> > Requirement already satisfied: annotated-types==0.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (0.6.0)
> > Collecting anyio==4.2.0 (from -r requirements.txt (line 8))
> > Downloading anyio-4.2.0-py3-none-any.whl (85 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 kB 9.1 MB/s eta 0:00:00
> > Requirement already satisfied: appdirs==1.4.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (1.4.4)
> > Collecting appnope==0.1.3 (from -r requirements.txt (line 10))
> > Downloading appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
> > Collecting asttokens==2.4.1 (from -r requirements.txt (line 11))
> > Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
> > Requirement already satisfied: async-timeout==4.0.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (4.0.3)
> > Requirement already satisfied: attrs==23.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (23.2.0)
> > Collecting backoff==2.2.1 (from -r requirements.txt (line 14))
> > Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
> > Collecting beautifulsoup4==4.12.2 (from -r requirements.txt (line 15))
> > Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 15.8 MB/s eta 0:00:00
> > Collecting bitsandbytes==0.41.0 (from -r requirements.txt (line 16))
> > Downloading bitsandbytes-0.41.0-py3-none-any.whl (92.6 MB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.6/92.6 MB 9.5 MB/s eta 0:00:00
> > Requirement already satisfied: bleach==6.1.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 17)) (6.1.0)
> > Collecting blinker==1.7.0 (from -r requirements.txt (line 18))
> > Downloading blinker-1.7.0-py3-none-any.whl (13 kB)
> > Requirement already satisfied: blis==0.7.11 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 19)) (0.7.11)
> > Requirement already satisfied: cachetools==5.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 20)) (5.3.2)
> > Requirement already satisfied: catalogue==2.0.10 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 21)) (2.0.10)
> > Collecting certifi==2023.11.17 (from -r requirements.txt (line 22))
> > Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 17.5 MB/s eta 0:00:00
> > Requirement already satisfied: charset-normalizer==3.3.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 23)) (3.3.2)
> > Requirement already satisfied: click==8.1.7 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 24)) (8.1.7)
> > Requirement already satisfied: cloudpathlib==0.16.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 25)) (0.16.0)
> > Collecting cohere==4.40 (from -r requirements.txt (line 26))
> > Downloading cohere-4.40-py3-none-any.whl (51 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.7/51.7 kB 5.2 MB/s eta 0:00:00
> > Collecting comm==0.2.0 (from -r requirements.txt (line 27))
> > Downloading comm-0.2.0-py3-none-any.whl (7.0 kB)
> > Requirement already satisfied: confection==0.1.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 28)) (0.1.4)
> > Requirement already satisfied: contourpy==1.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 29)) (1.2.0)
> > Requirement already satisfied: cycler==0.12.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 30)) (0.12.1)
> > Requirement already satisfied: cymem==2.0.8 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 31)) (2.0.8)
> > Collecting dataclasses-json==0.5.14 (from -r requirements.txt (line 32))
> > Downloading dataclasses_json-0.5.14-py3-none-any.whl (26 kB)
> > Collecting datasets==2.16.1 (from -r requirements.txt (line 33))
> > Downloading datasets-2.16.1-py3-none-any.whl (507 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 43.4 MB/s eta 0:00:00
> > Collecting debugpy==1.8.0 (from -r requirements.txt (line 34))
> > Downloading debugpy-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 71.0 MB/s eta 0:00:00
> > Collecting decorator==5.1.1 (from -r requirements.txt (line 35))
> > Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
> > Collecting Deprecated==1.2.14 (from -r requirements.txt (line 36))
> > Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
> > Collecting dill==0.3.7 (from -r requirements.txt (line 37))
> > Downloading dill-0.3.7-py3-none-any.whl (115 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 12.4 MB/s eta 0:00:00
> > Requirement already satisfied: diskcache==5.6.3 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 38)) (5.6.3)
> > Collecting distro==1.9.0 (from -r requirements.txt (line 39))
> > Downloading distro-1.9.0-py3-none-any.whl (20 kB)
> > Collecting dnspython==2.4.2 (from -r requirements.txt (line 40))
> > Downloading dnspython-2.4.2-py3-none-any.whl (300 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.4/300.4 kB 23.6 MB/s eta 0:00:00
> > Collecting docarray==0.32.1 (from -r requirements.txt (line 41))
> > Downloading docarray-0.32.1-py3-none-any.whl (215 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.3/215.3 kB 22.1 MB/s eta 0:00:00
> > Collecting docker-pycreds==0.4.0 (from -r requirements.txt (line 42))
> > Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
> > Collecting einops==0.6.1 (from -r requirements.txt (line 43))
> > Downloading einops-0.6.1-py3-none-any.whl (42 kB)
> > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 4.2 MB/s eta 0:00:00
> > Requirement already satisfied: entrypoints==0.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 44)) (0.4)
> > Requirement already satisfied: exceptiongroup==1.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 45)) (1.2.0)
> > Collecting executing==2.0.1 (from -r requirements.txt (line 46))
> > Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
> > ERROR: Could not find a version that satisfies the requirement faiss==1.7.4 (from versions: none)
> > ERROR: No matching distribution found for faiss==1.7.4
> 
> Any idea how to fix it?
> 
> Thanks in advance.

change it with ```faiss-cpu=1.7.4```

**Comment by tosettil-polimi** [comment]
@kinivi there is another error installing ```xformers===0.0.20``` requirement:

`Collecting xformers==0.0.20 (from -r requirements.txt (line 225))
  Using cached xformers-0.0.20.tar.gz (7.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/tosettil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/tosettil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/tosettil/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/cg/595nq3k16n5clr8pd8f004sh0000gn/T/pip-build-env-q9u9vl3p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/cg/595nq3k16n5clr8pd8f004sh0000gn/T/pip-build-env-q9u9vl3p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/cg/595nq3k16n5clr8pd8f004sh0000gn/T/pip-build-env-q9u9vl3p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/cg/595nq3k16n5clr8pd8f004sh0000gn/T/pip-build-env-q9u9vl3p/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

I have a Mac M1 Pro, do you happen to know how to fix it?

**Comment by UriBarkan** [comment]
> sorry for the late reply, try to remove versions int he requirements.txt and try again

Tried it, still got the following error on Google Colab:
```
ERROR: Could not find a version that satisfies the requirement faiss (from versions: none)
ERROR: No matching distribution found for faiss
```
[requirements_no_versions.txt](https://github.com/kinivi/AlchemyLab/files/14470250/requirements_no_versions.txt)

Attached the modified requirements file (w/o the version numbers).

**Comment by kinivi** [comment]
@UriBarkan colab has some problems with faiss, please refer to this solution

https://github.com/facebookresearch/faiss/issues/890#issuecomment-646009686

**Comment by UriBarkan** [comment]
> @UriBarkan colab has some problems with faiss, please refer to this solution
> 
> [facebookresearch/faiss#890 (comment)](https://github.com/facebookresearch/faiss/issues/890#issuecomment-646009686)

Sorry, followed the instructions on the above comment, to no avail. Also, I get the same error when I run it on my local machine.
